### PR TITLE
Add bouncing ball example

### PR DESCRIPTION
**Pull request by olivier-goury**
Add an example to be used for testing contact reduction.

### CODE REVIEW

**Comment by VannesteFelix** [comment]
Yes a video ! 
Accept form that is it possible to put this example into the **examples/others/** folder ?
Or create a specific one for collision because I guess it's collision reduction right ?

**Comment by olivier-goury** [comment]
Video? :
https://github.com/user-attachments/assets/abed8fef-5f70-45fe-9a29-485d59eb666c

**Comment by olivier-goury** [comment]
> Yes a video ! Accept form that is it possible to put this example into the **examples/others/** folder ? Or create a specific one for collision because I guess it's collision reduction right ?

Pour l'instant c'est une scene reduite normale, pas de reduction de contact

**Comment by alxbilger** [comment]
@olivier-goury Can you rebase this branch in order to get the latest changes?

**Pull request merged**
