### PR TITLE
[CI] Pass SOFA version to full

### PR DESCRIPTION
**Pull request by hugtalbot**

### CODE REVIEW

**Comment by alxbilger** [comment]
In my opinion, we need to compile and ship both standard and full.

**Comment by damienmarchal** [comment]
To me the full version only exists because have don't have a working package manager tracking dependencies.

**Comment by VannesteFelix** [comment]
@alxbilger @damienmarchal so do we allow both standard and full while waiting for a working package manager or do we stay with the current configuration ?

**Comment by alxbilger** [comment]
@hugtalbot for what reason do you need to go with SOFA full?

**Pull request closed without merging**
